import streamlit as st
from datetime import datetime

def generate_structured_report():
    st.markdown('<p class="section-header">📄 Structured Report Generator</p>', 
                unsafe_allow_html=True)
    
    st.markdown("""
    Generate a structured radiology report following the systematic approach.
    Based on: Klein JS, Guilleman RP. Systematic Approach to Chest Radiographic Analysis.
    """)
    
    with st.form("report_form"):
        col1, col2 = st.columns(2)
        with col1:
            patient_id = st.text_input("Patient ID")
            exam_date = st.date_input("Examination Date", datetime.now())
            indication = st.text_input("Clinical Indication")
        
        with col2:
            technique = st.selectbox("Technique:", 
                                   ["PA and Lateral", "AP Portable", "Lateral only"])
            comparison = st.text_input("Comparison (prior studies)")
        
        st.markdown("---")
        
        # Technical quality
        st.subheader("TECHNICAL QUALITY")
        tech_quality = st.text_area("Assessment:", 
                                  value="Positioning: ___ Penetration: ___ Inspiration: ___ Motion: ___")
        
        # Findings by system
        st.subheader("FINDINGS")
        
        devices = st.text_area("Support/Monitoring Devices:")
        chest_wall = st.text_area("Chest Wall:")
        mediastinum = st.text_area("Mediastinum:")
        hila = st.text_area("Hila:")
        lungs = st.text_area("Lungs and Pleura:")
        airways = st.text_area("Airways:")
        diaphragm = st.text_area("Diaphragm and Costophrenic Angles:")
        
        st.subheader("IMPRESSION")
        impression = st.text_area("Summary and Recommendations:")
        
        submitted = st.form_submit_button("Generate Report")
    
    if submitted:
        report = f"""
        CHEST RADIOGRAPH REPORT
        
        Patient ID: {patient_id}
        Date: {exam_date}
        Technique: {technique}
        Indication: {indication}
        Comparison: {comparison}
        
        TECHNICAL QUALITY:
        {tech_quality}
        
        FINDINGS:
        
        Support/Monitoring Devices:
        {devices if devices else "None identified."}
        
        Chest Wall:
        {chest_wall if chest_wall else "Normal."}
        
        Mediastinum:
        {mediastinum if mediastinum else "Normal."}
        
        Hila:
        {hila if hila else "Normal."}
        
        Lungs and Pleura:
        {lungs if lungs else "Normal."}
        
        Airways:
        {airways if airways else "Normal."}
        
        Diaphragm:
        {diaphragm if diaphragm else "Normal."}
        
        IMPRESSION:
        {impression}
        
        Report generated by CXR Learning System
        """
        
        st.markdown("---")
        st.code(report, language="text")
        
        st.download_button(
            label="Download Report",
            data=report,
            file_name=f"CXR_Report_{patient_id}_{exam_date}.txt",
            mime="text/plain"
        )
